name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello World"
        - run: echo "Hello World 2"
        - run: echo "Hello World 3"