name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MY_HOST: https://github.com
  COMPANY_NAME: "Debuggingsofft Env"
jobs:
    build-job:
      runs-on: ubuntu-latest
      env:
        MY_SCOPE: "build"
      steps:
        - run: echo "Var ${{ vars.COMPANY_NAME }} Env ${{env.COMPANY_NAME}}"
        - run: echo "My Host is ${{ env.MY_HOST }} at ${{env.MY_SCOPE}}"
        - run: echo "build-job ${{ github.repository }} by ${{ github.actor }} at ${{env.MY_SCOPE}}"
    
    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "test-job ${{ github.repository}}"

    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - run: echo "deploy-job ${{ job.status }}"