name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MY_HOST: https://github.com
jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "My Host is ${{ env.MY_HOST }}"
        - run: echo "build-job ${{ github.repository }} by ${{ github.actor }}"
    
    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "test-job ${{ github.repository}}"

    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - run: echo "deploy-job ${{ job.status }}"